[project]
name = "csv-analyzer"
version = "0.1.0"
description = "Analisador de arquivos CSV"

dependencies = [
    "pandas",
    "matplotlib",
    "fpdf"
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
